@host= http://localhost:5088
POST {{host}}/auth/register
Content-Type: application/json

{
    "firstname": "Jose Miguel",
    "lastname":  "Zayas Pérez",
    "email": "nex25k@gmail.com",
    "password": "123mvsdn213",
    "ci": "01121765364",
    "phonenumber": "+5354388544",
    "address": "D'Beche, Guanabacoa, La Habana"
}