@host= http://localhost:5000
POST {{host}}/auth/update
Content-Type: application/json

{
    "id": "1250bd0e-1256-4fb7-8729-4871c5066776",
    "firstname": "Laura Maria editada",
    "lastname":  "Ramona",
    "email": "lmariar@gmail.com",
    "ci": "02101576475",
    "address": "Calle 1 #123",
    "phonenumber": "787-123-1234",
    "password": "123mn213"
}