@host= http://localhost:5000
POST {{host}}/auth/update
Content-Type: application/json

{
    "id": "45f69513-a5ce-41ba-9fb0-117f091251e6",
    "firstname": "Laura Maria",
    "lastname":  "Ramona",
    "email": "lmariar@gmail.com",
    "ci": "02101576475",
    "address": "Calle 1 #123",
    "phonenumber": "787-123-1234",
    "password": "123mn21"
}